[package]
name = "frevi"
version = "0.4.0-pre4"
edition = "2024"

[dependencies]
chrono = "0.4.41"
crossterm = "0.29.0"
dirs = "6.0.0"
mlua = { version = "0.10.5", features = ["lua54"] }
ratatui = "0.29.0"
